# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: OpenSSF Scorecard

on:
  # For Branch-Protection check. Only the default branch is supported.
  branch_protection_rule:
  # To keep the Maintained check fresh.
  schedule:
    - cron: "34 14 * * 1"
  push:
    branches:
      - main

# Default to read-only permissions.
permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    # publish_results only succeeds from the default branch.
    if: github.ref_name == github.event.repository.default_branch
    permissions:
      security-events: write
      id-token: write
      # Uncomment if running in a private repo.
      # contents: read
      # actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
          # To enable the Branch-Protection check on public repos or
          # run against private repos, provide a fine-grained PAT:
          # repo_token: ${{ secrets.SCORECARD_TOKEN }}

      - name: Upload Scorecard results artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: scorecard-results
          path: results.sarif
          retention-days: 5

      - name: Upload to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
